package:
  name: ws-handler
  version: 0.2.0

build:
  number: 0
  noarch: true

source:
  path: .

requirements:
  run:
    - qutil
    - req

about:
  home: https://github.com/jonathonmcmurray/ws.q
  license: MIT
  summary: Module for WebSocket connection handling
